services:
  mysql:
    image: mysql:8.0
    container_name: reportit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportit_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: reportit-mongodb
    ports:
      - "27017:27017"
    volumes:
      - reportit_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  reportit_mongo_data:
