$ErrorActionPreference = "Stop"

$backendRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$authService = Join-Path $backendRoot "auth-service"
$mvn = "$env:TEMP\apache-maven-3.9.6\bin\mvn.cmd"
if (-not (Test-Path $mvn)) {
    $mvn = "C:\Users\jothi\Downloads\apache-maven-3.9.16-bin\apache-maven-3.9.16\bin\mvn.cmd"
}

if (-not (Test-Path $mvn)) {
    Write-Host "Maven not found. Update the Maven path in this script."
    exit 1
}

Write-Host ""
Write-Host "ReportIt OTP Mail Setup"
Write-Host "Use Gmail SMTP with your ReportIt project Gmail account."
Write-Host ""

$hostName = Read-Host "SMTP host"
if ([string]::IsNullOrWhiteSpace($hostName)) { $hostName = "smtp.gmail.com" }

$port = Read-Host "SMTP port, usually 587"
if ([string]::IsNullOrWhiteSpace($port)) { $port = "587" }

$username = Read-Host "SMTP username"
if ([string]::IsNullOrWhiteSpace($username)) { $username = "reportit.noreply@gmail.com" }
$from = Read-Host "From address"
if ([string]::IsNullOrWhiteSpace($from)) { $from = $username }

$securePassword = Read-Host "SMTP password or app password" -AsSecureString
$passwordPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword)
try {
    $password = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($passwordPtr)
} finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($passwordPtr)
}
$password = $password -replace "\s", ""

if ([string]::IsNullOrWhiteSpace($username) -or [string]::IsNullOrWhiteSpace($password)) {
    Write-Host "Username and password are required. OTP email cannot be sent without them."
    exit 1
}

if ($password.Length -lt 16 -or $password -eq "*") {
    Write-Host ""
    Write-Host "Invalid Gmail App Password."
    Write-Host "Paste the 16-character App Password generated by Google, not '*' and not your normal Gmail password."
    Write-Host "Example length after spaces are removed: 16 characters."
    exit 1
}

Write-Host "Stopping old auth-service processes..."
$authProcesses = Get-CimInstance Win32_Process -Filter "Name = 'java.exe'" |
    Where-Object { $_.CommandLine -like "*reportit-backend*auth-service*" } |
    Select-Object -ExpandProperty ProcessId

$portProcesses = @()
try {
    $portProcesses = Get-NetTCPConnection -LocalPort 8081 -State Listen -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty OwningProcess -Unique
} catch {
    $portProcesses = @()
}

$processesToStop = @($authProcesses + $portProcesses) |
    Where-Object { $_ } |
    Select-Object -Unique

if ($processesToStop) {
    Stop-Process -Id $processesToStop -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

$env:REPORTIT_MAIL_HOST = $hostName
$env:REPORTIT_MAIL_PORT = $port
$env:REPORTIT_MAIL_USERNAME = $username
$env:REPORTIT_MAIL_PASSWORD = $password
$env:REPORTIT_MAIL_FROM = $from
$env:SPRING_PROFILES_ACTIVE = if ($env:SPRING_PROFILES_ACTIVE) { $env:SPRING_PROFILES_ACTIVE } else { "local" }

Write-Host ""
Write-Host "Starting auth-service with ReportIt SMTP..."
Write-Host "From: $env:REPORTIT_MAIL_FROM"
Write-Host "SMTP: $env:REPORTIT_MAIL_HOST:$env:REPORTIT_MAIL_PORT"
Write-Host ""

Set-Location $authService
& $mvn spring-boot:run
