server:
  port: 8082

spring:
  application:
    name: user-management-service
  profiles:
    active: mysql

jwt:
  secret: ReportItSecretKeyForJWT2026MustBeAtLeast256BitsLong!!

cors:
  allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:3000

file:
  upload-dir: ./uploads

auth:
  service-url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/reportit_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Jothisreerc@14
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true